### PR TITLE
[RESEARCH] SQL generation script prototype

### PR DESCRIPTION
**Pull request by lacca0**
For #348. I left it in a test format, delete prints and coloring before usage

### CODE REVIEW

**Comment by lacca0** [comment]
image
The usage example, sorry for abusing that friendly chef example:)

**Comment by darabos** [comment]
> The usage example, sorry for abusing that friendly chef exercise:)

That's not a great example — the `edges` table already has an `src_name`/`dst_name` column, ideally the generated SQL should use that instead of running a join. (Check out the [docs](https://lynxkite.com/docs/latest/user-guide/#sql1) for a description of the available tables.)

**Comment by lacca0** [comment]
In my experience Codex (as opposed to GPT-3) uses WHERE more often than JOIN, I'm not sure why. Is it better in any sense?
image

**Comment by darabos** [comment]
Thanks! The spirit of this lives on in #353.

**Pull request closed without merging**
