### PR TITLE
Upgrade JavaScript dependencies

### PR DESCRIPTION
**Pull request by darabos**
#7 was automatically closed when I fixed the email addresses in the Git history. I've cherry-picked the same commits here. It's still not ready, but I still intend to finish this when I get around to it.

### CODE REVIEW

**Comment by xandrew** [comment]
Is this ready now, shall I review?

**Comment by darabos** [comment]
> Is this ready now, shall I review?

Yes, thank you.

**Comment by xandrew** [comment]
> shall I review?

Looks like this was just a trick question - sorry for being slow.

LGTM! :)

**Comment by darabos** [comment]
I'll have to come back to this at some point. Closing for now.

**Pull request closed without merging**
